const ROUTES = {
  plotter: '/plotter',
  fourier: '/fourier',
  fractal: '/fractal',
  montecarlo: '/monte-carlo',
  bezier: '/bezier',
  flowfield: '/flow',
  life: '/cellular-automata',
  lissajous: '/lissajous',
  pendulum: '/double-pendulum',
  voronoi: '/voronoi',
}

export const ALGOS = [
  { key: 'plotter', idx: '01', name: '3D Function Plotter', meta: 'Surfaces & gradient descent in 3D',
    eq: 'ƒ(x, y) = x² − y²', tags: ['3D', 'real-time', 'gradient'], route: ROUTES.plotter,
    desc: 'Render saddle points and surfaces in 3D, then run gradient descent across the landscape.' },
  { key: 'fourier', idx: '02', name: 'Fourier Transform', meta: 'Signals as sums of rotating epicycles',
    eq: 'ƒ(t) = Σ aₙ·sin(nωt)', tags: ['signal', 'harmonics'], route: ROUTES.fourier,
    desc: 'Decompose a waveform into rotating circles and watch the harmonics reconstruct the signal.' },
  { key: 'fractal', idx: '03', name: 'Fractal', meta: 'Recursive, self-similar structure',
    eq: 'z ↦ z² + c', tags: ['recursion', 'L-system'], route: ROUTES.fractal,
    desc: 'Grow self-similar structures through recursion — infinite detail from a single rule.' },
  { key: 'montecarlo', idx: '04', name: 'Monte Carlo', meta: 'Integration by random sampling',
    eq: 'π ≈ 4 · (inside / total)', tags: ['probability', 'sampling'], route: ROUTES.montecarlo,
    desc: 'Estimate areas and integrals by scattering random samples and counting what lands inside.' },
  { key: 'bezier', idx: '05', name: 'Bézier Curves', meta: 'Parametric curves via de Casteljau',
    eq: 'B(t) = Σ (ₙᵢ)(1−t)ⁿ⁻ⁱtⁱ Pᵢ', tags: ['parametric', 'spline'], route: ROUTES.bezier,
    desc: 'Shape smooth parametric curves and watch the de Casteljau construction trace each point.' },
  { key: 'flowfield', idx: '06', name: 'Perlin Flow Field', meta: 'Particles steered by smooth noise',
    eq: 'θ(x, y) = noise(x, y) · 2π', tags: ['noise', 'procedural'], route: ROUTES.flowfield,
    desc: 'Steer thousands of particles through a smooth pseudo-random vector field to reveal organic flow.' },
  { key: 'life', idx: '07', name: 'Cellular Automata', meta: "Conway's Game of Life",
    eq: 'rule  B3 / S23', tags: ['automata', 'emergence'], route: ROUTES.life,
    desc: 'Four simple birth-and-survival rules on a grid give rise to gliders, oscillators and chaos.' },
  { key: 'lissajous', idx: '08', name: 'Lissajous Figures', meta: 'Two perpendicular oscillations',
    eq: 'x = sin(at+δ),  y = sin(bt)', tags: ['parametric', 'harmonic'], route: ROUTES.lissajous,
    desc: 'Trace the interference of two perpendicular oscillations into slowly morphing harmonic loops.' },
  { key: 'pendulum', idx: '09', name: 'Double Pendulum', meta: 'Deterministic chaos',
    eq: 'θ̈ = ƒ(θ₁, θ₂, ω)', tags: ['chaos', 'dynamics'], route: ROUTES.pendulum,
    desc: 'A minuscule change in the starting angle explodes into wildly different motion — pure chaos.' },
  { key: 'voronoi', idx: '10', name: 'Voronoi Diagram', meta: 'Regions of nearest influence',
    eq: 'V(pᵢ) = { x : |x−pᵢ| ≤ |x−pⱼ| }', tags: ['geometry', 'spatial'], route: ROUTES.voronoi,
    desc: 'Partition the plane into cells of nearest influence — the geometric dual of Delaunay.' },
]
